package com.silverphone.app.platform.transfer

import android.content.Context
import com.silverphone.app.domain.ContactLimits
import java.io.File
import java.util.UUID

/**
 * The three bounded working directories, all under the app's private cache.
 *
 * Names inside them are always generated by this class, never taken from an
 * archive entry name. Only `exports/` is exposed through the share provider;
 * staging and drafts are unreachable from outside the app.
 */
class TransferDirs(context: Context) {

    private val cacheDir: File = context.applicationContext.cacheDir

    val exportsRoot: File get() = File(cacheDir, "exports")

    val stagingRoot: File get() = File(cacheDir, "import-staging")

    val draftsRoot: File get() = File(cacheDir, "photo-drafts")

    fun newExportDirectory(): File = newDirectory(exportsRoot)

    fun newStagingDirectory(): File = newDirectory(stagingRoot)

    fun newDraftDirectory(): File = newDirectory(draftsRoot)

    private fun newDirectory(root: File): File {
        val directory = File(root, UUID.randomUUID().toString())
        directory.mkdirs()
        return directory
    }

    /**
     * Removes stale working directories.
     *
     * Something in use is never deleted: an export younger than the share window
     * is kept so a receiving app still has time to read it, and a staging
     * directory created during the current operation is kept because it is too
     * new to expire.
     */
    fun cleanUp(now: Long = System.currentTimeMillis()) {
        purge(draftsRoot, now, maxAgeMillis = 0L)
        purge(stagingRoot, now, maxAgeMillis = 0L)
        purge(exportsRoot, now, maxAgeMillis = ContactLimits.EXPORT_CACHE_TTL_MILLIS)
    }

    private fun purge(root: File, now: Long, maxAgeMillis: Long) {
        val children = root.listFiles() ?: return
        for (child in children) {
            val age = now - child.lastModified()
            if (age > maxAgeMillis) {
                child.deleteRecursively()
            }
        }
        // Remove the empty roots so the cache does not grow directories forever.
        if (root.listFiles()?.isEmpty() == true) root.delete()
    }
}
